openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
  description: |
    Public API specification for the service. It covers user registration,
    job retrieval and WebSocket usage.
servers:
  - url: https://api.example.com
    description: Production server
paths:
  /auth/register:
    post:
      summary: Register a new user
      description: Create an account and receive an authentication token.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: Successfully created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid input data
      security: []
  /jobs:
    get:
      summary: Query jobs
      description: |
        Returns a paginated list of jobs. Requires authentication.
      tags:
        - Jobs
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: limit
          schema:
            type: integer
            default: 20
          description: Number of jobs per page
      responses:
        '200':
          description: List of jobs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedJobs'
      security:
        - BearerAuth: []
  /jobs/{id}:
    get:
      summary: Get job by ID
      tags:
        - Jobs
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Job details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Job'
        '404':
          description: Job not found
      security:
        - BearerAuth: []
  /ws/jobs:
    get:
      summary: Job updates via WebSocket
      description: |
        Upgrade to a WebSocket connection to receive job status updates.
        Send an authentication token as a query parameter or header when connecting.
      tags:
        - WebSocket
      responses:
        '101':
          description: Switching protocols
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    RegisterRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    AuthTokenResponse:
      type: object
      properties:
        token:
          type: string
    Job:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
        createdAt:
          type: string
          format: date-time
    PaginatedJobs:
      type: object
      properties:
        page:
          type: integer
        totalPages:
          type: integer
        jobs:
          type: array
          items:
            $ref: '#/components/schemas/Job'
      required:
        - page
        - totalPages
        - jobs
